apiVersion: v1
kind: pod
metadata:
  name: influxdb
spec:
  volumes:
    - name: "influxdb-data"
      hostPath:
        path: "/var/lib/influxdb"
  containers:
    - image: b.gcr.io/kuar/influxdb:0.9.4.2
      name: influxdb
      volumeMounts:
        - mountPath: ".influxdb"
          name: "influxdb-data"
      ports:
        - containerPort: 8083
          name: admin 
          protocol: TCP
        - containerPort: 8086
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /ping
          port: 8086
        initialDelaySeconds: 5
        timeoutSeconds: 1
      readinessProbe:
        httpGet:
          path: /ping
          port: 8086
        initialDelaySeconds: 15
        timeoutSeconds: 1
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"

