apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: prebidserver-deployment
spec:
  replicas: 10
  template:
    metadata:
      labels:
        run: my-prebidserver
    spec:
      containers:
      - name: my-prebidserver
        image: grissonz/prebid-server
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: prebidserver-svc
  labels:
    run: my-prebidserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    run: my-prebidserver