apiVersion: v1
kind: Service
metadata:
  name: prebidserver-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: prebidserver-frontend
    env: test