apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: prebidserver-deployment
  labels:
    env: test
    version: 0.01
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: prebidserver-frontend
        env: test
    spec:
      containers:
      - name: prebidserver-frontend
        image: grissonz/prebid-server
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prebidserver-svc
  labels:
    env: test
    version: 0.01
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: prebidserver-frontend
    env: test