apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mediation-deployment
spec:
  replicas: 32
  template:
    metadata:
      labels:
        svc: mediationservice
    spec:
      containers:
      - name: mediationserviceimage
        image: mediationhubint.azurecr.io/dev/mediation:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mediation-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    svc: mediationservice